name: Crowdin Action

on:
  workflow_dispatch:
  push: 
    paths:
      - ".github/workflows/*"
  schedule: 
     - cron: '0 */12 * * *'
  

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: false
          download_translations: true
          # config: "crowdin.yml"
          # crowdin.yml 原内容：
          # files:
          #   - source: /zh_CN.xaml
          #     translation: /Language/%locale_with_underscore%.xaml
          source: /zh_CN.xaml
          translation: /Language/%locale_with_underscore%.xaml
          download_translations_args: "--preserve-hierarchy --all --pseudo"
          export_only_approved: true
          localization_branch_name: crowdin-pending
          # 暂时设置手动打开并合并 PR
          create_pull_request: false
          # pull_request_title: '[Crowdin] New Translations'
          # pull_request_body: 'New Crowdin translations available'
          # pull_request_base_branch_name: 'main'
        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
